server:
  port: 5000
management:
  server:
    port: 9300
    
spring:
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)  
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dptrackdb.clrfmtnhaboz.us-east-1.rds.amazonaws.com:3306/dptrack?createDatabaseIfNotExist=true
    username: dptrack
    password: password
  jpa:          
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect

# Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update

          